version: "2"
services:
    rabbitmq:
        image: rabbitmq
        ports:
          - "5672:5672"
        hostname: rabbitmq
        network_mode: "host"
    mariadb:
        image: mariadb
        hostname: mariadb
        environment:
          - MYSQL_ROOT_PASSWORD=password
        volumes:
            - ./db_data:/var/lib/mysql
            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        network_mode: "host"
        ports:
          - 3306:3306
    cinder-api:
        image: cinder
        hostname: cinder-api
        volumes:
            - ../../etc/cinder:/etc/cinder
            - ./init-scripts:/init-scripts
        ports:
            - 8776:8776
        depends_on:
          - mariadb
        network_mode: "host"
        command: sh /init-scripts/cinder-api.sh
    cinder-scheduler:
        image: cinder
        hostname: cinder-scheduler
        volumes:
            - ../../etc/cinder:/etc/cinder
        depends_on:
          - rabbitmq
          - cinder-api
        network_mode: "host"
        depends_on:
          - cinder-api
        restart: on-failure
        command: bash -c "sleep 30 && cinder-scheduler -d"

    cinder-volume:
        image: cinder-volume
        hostname: cinder-volume-lvm
        privileged: true
        volumes:
            - ../../etc/cinder:/etc/cinder
            - /dev/:/dev/
            - /run/:/run/:shared
            - /etc/localtime:/etc/localtime:ro
            - /lib/modules:/lib/modules:ro
        depends_on:
          - cinder-scheduler
        ports:
            - 3260:3260
        network_mode: "host"
        restart: on-failure
        command: bash -c "sleep 30 && /usr/sbin/tgtd && cinder-volume -d"
